### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by dkess** [ocf/labmap#2]
This is all JavaScript now, but TypeScript is a generally nicer to use language. It would be great if we could use it instead.

We might also need a larger build process for this, perhaps using Gulp or one of the other JS tools? However I'm not well-versed in this space so I don't know what's popular nowadays.

**Comment by kpengboy** [comment]
I'm -0 on this. To me, this project seems not complex enough for the benefits of TypeScript to be worth the extra build hoops. But I wouldn't mind if someone set it up.

**Comment by dkess** [comment]
Sure, it's not a priority for me, but if someone sees this and is interested then I'd definitely approve it.

**Comment by emmatyping** [comment]
This is done in https://github.com/ocf/labmap/pull/4.
