### ISSUE TITLE
If a machine is occupied, show the ocf account name of the logged in user

### ISSUE THREAD

**Issue by MrMinos** [ocf/labmap#8]
This would be useful for opstaff who needs to refund pages. Maybe should limit showing the account names only to ocf ip address range?

**Comment by dkess** [comment]
This would be a pretty big privacy issue, I think it's fine to just have users self-report their username. We could also build this into the paper refund command (refund pages to user at machine) though I think it's equally annoying to find out the name of a desktop a user is on...

**Comment by cg505** [comment]
Maybe we could just print out a map for opstaff desk and then let opstaff use `last-lab`.

**Comment by MrMinos** [comment]
Hmmm aside from privacy issue since we can just limit access to opstaff desk; this may not be a big enough problem to solve, but having this would help with opstaff UX.

Come to think of it, maybe make the each machine on the map clickable and enable refund for the current logged in user?

**Comment by raymondnumbergenerator** [comment]
I think the thing is if a user comes up to opstaff asking for page refunds it's easier for the user to just state their username than to point out which machine they're logged in to.

I also agree with dkess about this being a privacy issue.

**Comment by MrMinos** [comment]
> I think the thing is if a user comes up to opstaff asking for page refunds it's easier for the user to just state their username than to point out which machine they're logged in to.

I agree on that it's likely the case when the username is short; also with long usernames maybe opstaff don't find it much of a hassle. It's a nice-to-have and a step towards a graphical solution for opstaff paper refund as mentioned [here](https://github.com/ocf/utils/issues/96).

Also why is it actually a privacy issue if we limit access to only ocf ip range, or limit to opstaff/ocfstaff group?

**Comment by dkess** [comment]
It's fine if we limit such a feature to opstaff/ocfstaff group, though writing a mechanism to enforce these permissions is harder, especially since I'd like this webapp to not rely on other parts of OCF infra. Doing this kind of security based on IP addresses is not acceptable.

**Comment by TonyLianLong** [comment]
Is ncurses a possibility since it is graphical and hence easier to use? We don’t need to use labmap to do everything.

**Comment by dkess** [comment]
I wouldn't expect opstaff refunding pages to want to use such an interface. I think the "best" way to do this would be to somehow make a second version of this webapp that makes calls to another API for seeing who is on a desktop. That API would have to take Kerberos/LDAP authentication to be used.

This leaves a lot of questions unanswered though, and it's a lot of infra to build out for a feature I don't think we'd end up using.

**Comment by MrMinos** [comment]
I agree it's a marginal enhancement, but you never know. Maybe worth asking in opstaff meeting.

**Comment by MrMinos** [comment]
After talking to opstaff–Esha, a new take on this GitHub issue came up.

Most of the times, when users approach the opstaff for a refund, they've already sent the print job and _logged out_ of the computer, only to find that their print job is missing/rejected. So viewing the currently logged in user on the labmap won't help with majority of the refund request cases.

This was an amusing find, to learn that the real situation lies outside of the imagination.

Closing the issue with concerns of privacy and it won't help the opstaff as much due to the description above of how things go down in real life.
